import './globals.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
import { Inter } from 'next/font/google'
import Providers from './Components/Providers'

import Navbar from './Components/Navbar'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='h-screen w-screen overflow-x-hidden'>
        <Providers>
        <Navbar/>
        {children}
       </Providers>
      </body>
    </html>
  )
}
